# Generated by Django 2.0.6 on 2018-06-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('target', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ai1',
            },
        ),
    ]
