# Generated by Django 2.0.6 on 2018-06-13 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai1',
            name='counts',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
